spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: kkm
  profiles:
    active: config
  config:
    import: optional:configserver:http://172.18.0.2:8888