server:
  port: 3031
  address: localhost
spring:
  datasource:
    url: jdbc:mysql://ggmdb.c2rnm9avjkap.ap-northeast-2.rds.amazonaws.com:3306/TestKkm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ggmdb
    password: tnltmxpak
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace

token:
  secretKey: "dlrjtdmstlzmfltzlxhzmsdmlqlalfqjsghdlqslek"
debug: true